In [4]:
import numpy as np
from numpy.linalg import eig
from numpy.linalg import svd

In [5]:
M = np.matrix([[1,0,3],[3,7,2],[2,-2,8],[0,-1,1],[5,8,7]])
M_t = np.transpose(M)

In [6]:
print(M @ M_t)
print(M_t @ M)
val, vec = eig(M_t @ M)
print(val)
print(vec)

val, vec = eig(M @ M_t)
print(val)
print(vec)

[[ 10   9  26   3  26]
 [  9  62   8  -5  85]
 [ 26   8  72  10  50]
 [  3  -5  10   2  -1]
 [ 26  85  50  -1 138]]
[[ 39  57  60]
 [ 57 118  53]
 [ 60  53 127]]
[2.14670489e+02 9.32587341e-15 6.93295108e+01]
[[ 0.42615127  0.90453403 -0.01460404]
 [ 0.61500884 -0.30151134 -0.72859799]
 [ 0.66344497 -0.30151134  0.68478587]]
[ 2.14670489e+02 -8.88178420e-16  6.93295108e+01 -3.34838281e-15
  7.47833227e-16]
[[-0.16492942 -0.95539856  0.24497323 -0.54001979 -0.78501713]
 [-0.47164732 -0.03481209 -0.45330644 -0.62022234  0.30294097]
 [-0.33647055  0.27076072  0.82943965 -0.12704172  0.2856551 ]
 [-0.00330585  0.04409532  0.16974659  0.16015949  0.43709105]
 [-0.79820031  0.10366268 -0.13310656  0.53095405 -0.13902319]]


In [7]:
u, sigma, v_t = svd(M)
print(u)
print(sigma)
print(np.transpose(v_t))

[[-0.16492942 -0.24497323  0.9482579   0.09864471 -0.06214956]
 [-0.47164732  0.45330644 -0.02261948  0.08103373 -0.75165416]
 [-0.33647055 -0.82943965 -0.27341434 -0.18350729 -0.3006445 ]
 [-0.00330585 -0.16974659 -0.14522096  0.97468061  0.00915155]
 [-0.79820031  0.13310656 -0.06671416  0.00505374  0.58368021]]
[1.46516378e+01 8.32643446e+00 2.99921582e-16]
[[-0.42615127  0.01460404 -0.90453403]
 [-0.61500884  0.72859799  0.30151134]
 [-0.66344497 -0.68478587  0.30151134]]


In [8]:
r_u = u[:,:1]
r_sigma = [sigma[:1]]
r_v_t = v_t[:1,]
print(M @ np.transpose(r_v_t))

[[ -2.41648616]
 [ -6.91040562]
 [ -4.92984458]
 [ -0.04843612]
 [-11.69494183]]
